### ISSUE TITLE
Is not possible install playujs

### ISSUE THREAD

**Issue by dubo** [rafaelfelini/playujs-examples#1]
play deps 

Result:

---

play! 1.2.3, http://www.playframework.org

 Resolving dependencies using C:\app\work\playujs-examples\conf\dependencies.ym
,
 No dependencies to install

---

 WARNING: These dependencies are missing, your application may not work properl
 (use --verbose for details),

```
   playujs->playujs ->
```

---

 Some dependencies are still missing.

**Comment by rafaelfelini** [comment]
Hi Dubo sorry for the delay, the plugin was not published in play modules repository yet.
To work properly you'll need to download and use locally.
